project:
  type: website

website:
  title: "Óscar González-Velasco PhD"
  favicon: "images/icon.cluster.png"
  back-to-top-navigation: true

  navbar:
    logo: "images/icon.cluster.png"
    logo-href: index.qmd
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    grid:
      sidebar-width: 200px
      body-width: 900px
      margin-width: 100px
      gutter-width: 1.5rem
    theme: cosmo
    css: styles.css
    toc: true



