---
title: "" 
about:
  id: headingnorth
  template: jolla
  links:
    - icon: google
      text: google scholar
      href: https://scholar.google.com/citations?user=OwduvQQAAAAJ&hl=en
    - icon: github
      text: Github
      href: https://github.com/OscarGVelasco
    - icon: linkedin
      text: Linkedin
      href: https://www.linkedin.com/in/%C3%B3scar-gonz%C3%A1lez-velasco-04323264?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3B0i1RywokQ6iA5xDAGszu1A%3D%3D
    - icon: twitter
      text: twitter
      href: https://twitter.com/Oscar_Anpre
---

<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<font size="12"><center>
**Óscar González-Velasco, PhD**
</center></font>

<font size="6"><center>
***German Cancer Research Center DKFZ*** <br>
***Group of Applied Bioinformatics, Heidelberg.***
</center></font>

<center><p><a href="/images/CV_Gonzalez_Velasco_Oscar.pdf">Download CV</a></p></center>

:::{#headingnorth}

:::

## Current and Former Positions:

* June 2022–current. German Cancer Research Center DKFZ, group of Applied Bioinformatics, Heidelberg, Germany. AI Health Innovation Cluster postdoctoral interdisciplinary research program.
* June 2021–2022. CSIC Postdoctoral Scientist at Cancer Research Center (IBMCC-FICUS), Salamanca, Spain.
* January 2021. Research Stay, University of Heidelberg (Germany), Dr. Julio Saez-Rodriguez group.
* September 2016–2021. CSIC PhD candidate Scientist at Cancer Research Center (IBMCC-FICUS), Salamanca, Spain.
* December 2014–September 2016. Computer Engineer at INDRA Software Labs, Salamanca, Spain. O2 UK mobile infrastructure 

## Academic qualifications:

* 2016–2021. PhD in Bioinformatics (Cum Laude), Salamanca Cancer Research Center (IBMCC-FICUS), University of Salamanca. International Doctor Distinction.
* 2013–2014. Master of Science (MSc) in Intelligent Systems (Bioinformatics, Machine Learning, Artificial Intelligence and Data Science), University of Salamanca. 
* 2006–2012. Master’s degree in engineering (MEng) in Computer Science, University of Salamanca. 
* 2012. Bachelor of Science (BSc) in Computer Science (Second class Honours Upper division), University of the West of Scotland. 

## Scientific Publications:

* **González-Velasco Óscar**, Dulce Papy-García, Gael Le Douaron, José M. Sánchez-Santos, Javier De Las Rivas. Transcriptomic landscape, gene signatures and regulatory profile of aging in the human brain. BBA - Gene Regulatory Mechanisms, 2020, 194491. PMID: 32006715. [https://doi.org/10.1016/j.bbagrm.2020.194491](https://doi.org/10.1016/j.bbagrm.2020.194491){target="_blank"}
* **González-Velasco Óscar**, De Las Rivas Javier, Lacal Jesús. Proteomic and transcriptomic profiling identifies early developmentally regulated proteins in Dictyostelium discoideum. Cells 2019, 8, 1187. PMID: 31581556. [https://doi.org/10.3390/cells8101187](https://doi.org/10.3390/cells8101187){target="_blank"}
* Montero-Bullón Javier-Fernando, **González-Velasco Óscar**, Isidoro-García María, Lacal Jesús. Integrated in silico MS-based phosphoproteomics and network enrichment analysis of RASopathy proteins. Orphanet J Rare Dis 16, 303 (2021). [https://doi.org/10.1186/s13023-021-01934-x](https://doi.org/10.1186/s13023-021-01934-x){target="_blank"}
* Alonso-Moreda N, Berral-González A, De La Rosa E, **González-Velasco O**, Sánchez-Santos JM, De Las Rivas J. Comparative Analysis of Cell Mixtures Deconvolution and Gene Signatures Generated for Blood, Immune and Cancer Cells. International Journal of Molecular Sciences. 2023; 24(13):10765. [https://doi.org/10.3390/ijms241310765](https://doi.org/10.3390/ijms241310765){target="_blank"}



## Oral Communications and Poster presentations:

* Poster. Primary site identification of metastatic cancers using Deep Learning: applying explainable machine learning as a tool for biomolecular understanding. AI in Cancer Diagnostics: from research to clinical practice. European Association for Cancer Research (EACR). October 2021.
* Oral Presentation. Predicting progression and recurrence using Deep Learning in small cancer cohorts and application of Explainable Machine Learning as a tool to elucidate resistance to therapy. Oral presentation (2nd prize best oral presentation Early Career Scientist). New diagnostic and therapeutic tools against multidrug resistant tumors, STRATAGEM’s 4th Annual Conference. September 2021.
* Poster. A bioinformatic study of Single Cell RNA-seq data analysis protocols for the characterization of cell types of the central nervous system. Poster Communication. Conference XXXVIII SEIO (Spanish Society of Statistics & Operations Research). September 2019.

## Scholarships and professional distinctions:

* EMBO 2021 Short-Term Fellowship (fellowship id: 8927) for the support of a 3 months (January, 7 – April, 10) collaboration at the computational biomedicine laboratory of the University of Heidelberg (Germany) leaded by Dr. Julio Saez-Rodriguez.
* Molecular Oncology 2023 Writing Competition, Second Price for best assay in “Uniting disciplines to tackle cancer”: (https://febs.onlinelibrary.wiley.com/hub/journal/18780261/winner-second-prize-2023-molecular-oncology-writing-competition)
* PhD Fellow JCyL Research Scientist 2018 (4 years), 1.Nov.2018 - 1.Jul.2022. Funding Institution: JCyL and FEDER (European Regional Development Fund). Hosting Institution: CSIC (Consejo Superior de Investigaciones Científicas) and Cancer Research Center (IBMCC-FICUS).
* ERASMUS Mundus Scholarship (10 months), 1.Sep.2011 - 1.Jun.2012. Hosting University: University of the West of Scotland, UK.

## Leadership and teaching skills:

Trained and supervised Bachelor´s and Master´s students during PhD and PostDoc.
Teaching: lecture Introduction to RNA-Seq sequencing. Machine Learning course imparted by the Applied Bioinformatics Group, DKFZ.
